{{- range $cfgName := .Values.scanConfigurations }}
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ $name := print "bdba-" $cfgName }}{{ $name }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: bdba
      delivery-gear.gardener.cloud/service: bdba
      delivery-gear.gardener.cloud/cfg-name: {{ $cfgName }}
  template:
    metadata:
      labels:
        app: bdba
        delivery-gear.gardener.cloud/service: bdba
        delivery-gear.gardener.cloud/cfg-name: {{ $cfgName }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: bdba
      terminationGracePeriodSeconds: 1800 # 30 min
      containers:
        - name: bdba
          image: {{ include "image" $.Values.bdba.image }}
          imagePullPolicy: IfNotPresent
          command:
          - python3
          - -m
          - bdba
          env:
          - name: CFG_NAME
            value: {{ $cfgName }}
          {{- if default dict $.Values.envVars }}
          {{- range $key, $value := $.Values.envVars }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- end }}
          volumeMounts:
          - name: cfg-factory
            mountPath: "/cfg_factory"
            readOnly: true
          - name: features-cfg
            mountPath: "/features_cfg"
            readOnly: true
          lifecycle:
            preStop: # hook ensures that just created pods have at least enough time alive to add a termination signal handler
              exec:
                command:
                - sleep
                - "60"
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 600Mi
              cpu: 200m
      volumes:
        - name: cfg-factory
          secret:
            secretName: cfg-factory-secret
            optional: true
        - name: features-cfg
          secret:
            secretName: features-cfg
            optional: true
---
{{- end }}
