{{- range $cfgName := .Values.scanConfigurations }}
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ $name := print "issuereplicator-" $cfgName }}{{ $name }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: issue-replicator
      delivery-gear.gardener.cloud/service: issueReplicator
      delivery-gear.gardener.cloud/cfg-name: {{ $cfgName }}
  template:
    metadata:
      labels:
        app: issue-replicator
        delivery-gear.gardener.cloud/service: issueReplicator
        delivery-gear.gardener.cloud/cfg-name: {{ $cfgName }}
    spec:
      terminationGracePeriodSeconds: 300 # 5 min
      containers:
        - name: issue-replicator
          image: {{ include "image" .Values.issue-replicator.image }}
          imagePullPolicy: IfNotPresent
          command:
          - python3
          - -m
          - issue_replicator
          env:
          - name: CFG_NAME
            value: {{ $cfgName }}
          {{- if default dict $.Values.envVars }}
          {{- range $key, $value := $.Values.envVars }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- end }}
          volumeMounts:
          - name: cfg-factory
            mountPath: "/cfg_factory"
            readOnly: true
          - name: features-cfg
            mountPath: "/features_cfg"
            readOnly: true
          lifecycle:
            preStop: # hook ensures that just created pods have at least enough time alive to add a termination signal handler
              exec:
                command:
                - sleep
                - "60"
          resources:
            requests:
              memory: 150Mi
              cpu: 500m
            limits:
              memory: 300Mi
              cpu: 1000m
      volumes:
        - name: cfg-factory
          secret:
            secretName: cfg-factory-secret
            optional: true
        - name: features-cfg
          secret:
            secretName: features-cfg
            optional: true
---
{{- end }}
